// svkit/src/components/layout/endorsement.svelte
<script lang="ts">
    import Card from '../card';
    interface EndorsementProps extends ComponentProps<"div"> {
        person: string;
        personLink: string;
        text: string;
        hoverColor: string;
        className?: string;
    }
    let props: ButtonTypeProps = $props();
</script>

    
                    <Card {...props} className={`endorsement ${props.class || ""}`}>
                        <h3 id={`${props.id}-author`} aria-label={`${props["aria-label"]}-author`}>
                            <a id={`${props.id}-author-link`} aria-label={`${props["aria-label"]} Author Link`} title={`${props["aria-label"]} Author Link`} href={props.personLink} class={`text-hover-${props.hoverColor}`} target="_blank" rel="noopener noreferrer">{props.person}</a>
                        </h3>
                        <p id={`${props.id}-message`} aria-label={`${props["aria-label"]}-message`} class="p fit-width">&quot;{props.text}&quot;</p>
                    </Card>
            

<style lang="scss">
    .endorsement {
        width: 100%;
        @media screen and (min-width: device-max("md")) {
            width: 50%;
        }
    }
</style>

// src/components/layout/endorsement.tsx
import React, { ComponentProps } from 'react';
import Link from 'next/link';
import Card from '../card';

interface EndorsementProps extends ComponentProps<"div"> {
    person: string;
    personLink: string;
    text: string;
    hoverColor: string;
    className?: string;
}

const Endorsement = (props: EndorsementProps) => (
    
                    <Card className={`endorsement ${props.className || ""}`}>
                        <h3><Link href={props.personLink} className={`text-hover-${props.hoverColor}`} target="_blank" rel="noopener noreferrer">{props.person}</Link></h3>
                        <p className="p fit-width">&quot;{props.text}&quot;</p>
                    </Card>
            
);

export default Endorsement;
