// src/components/card.tsx
import {ComponentProps} from 'react';


export interface CardPropsType extends ComponentProps<"div"> {
    className?: string;
}

const Card = ({children, className, ...props}: CardPropsType) => (
    <div className={`card ${className}`} {...props}>
        {children}
    </div>
);

export default Card;

// src/components/card.svelte
<script lang="ts">
    import type { HTMLAttributes } from 'svelte/elements';
    export interface CardPropsType extends HTMLAttributes<HTMLDivElement> {
        className?: string;
    }
    let props: CardPropsType = $props();
</script>


    <div class={`card ${props.className}`} {...props}>
        {@render props.children?.()}
    </div>
