// svkit/src/components/layout/endorsement.svelte
<script lang="ts">
    import Card from '../card';
    interface EndorsementProps extends ComponentProps<"div"> {
        person: string;
        personLink: string;
        text: string;
        hoverColor: string;
        className?: string;
    }
    let props: ButtonTypeProps = $props();
</script>

    
                    <Card {...props} className={`endorsement ${props.class || ""}`}>
                        <h3 id={`${props.id}-author`} aria-label={`${props["aria-label"]}-author`}>
                            <a id={`${props.id}-author-link`} aria-label={`${props["aria-label"]} Author Link`} title={`${props["aria-label"]} Author Link`} href={props.personLink} class={`text-hover-${props.hoverColor}`} target="_blank" rel="noopener noreferrer">{props.person}</a>
                        </h3>
                        <p id={`${props.id}-message`} aria-label={`${props["aria-label"]}-message`} class="p fit-width">&quot;{props.text}&quot;</p>
                    </Card>
            

<style lang="scss">
    .endorsement {
        width: 100%;
        @media screen and (min-width: device-max("md")) {
            width: 50%;
        }
    }
</style>

// src/components/endorsement.tsx
import React, { ReactNode } from 'react';
import Link from 'next/link';
import { NextPage } from 'next';
import Card from './card';
//#0c0711
const Endorsement = ({person, personLink, text}: {person: string, personLink: string, text: ReactNode}) => (
    
                    <Card>
                        <h3><Link href={personLink} target="_blank" rel="noopener noreferrer">{person}</Link></h3>
                        <p className="p">&quot;{text}&quot;</p>
                    </Card>
            
);

export default Endorsement;
