// src/components/popMenu.tsx
import React, { ReactNode, useState } from 'react';

type PopMenuCommonProps = {
    children: ReactNode,
    className?: string,
    ariaLabel?: string,
    trigger: ReactNode
}


const PopMenu = ({children, className, ariaLabel, trigger} : PopMenuCommonProps) => {
    const [bodyDisplay, setBodyDisplay] = useState("none");
    return (
        <div aria-label={ariaLabel} className={`pop-menu-container ${className}`} onMouseLeave={() => setBodyDisplay("none")}>
            <div className="pop-menu-trigger" onMouseEnter={() => setBodyDisplay("flex")}>
                {trigger}
            </div>
            <div className="pop-menu-body bg-color-darker-bg" style={{display: bodyDisplay}}>
                {children}
            </div>
        </div>
    );
}

export default PopMenu;

// svkit/src/components/popMenu.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  interface PopMenuPropsType {
    id: string;
    className?: string;
    ariaLabel?: string;
    trigger: Snippet;
    body: Snippet;
    
  }
  let props: PopMenuPropsType = $props();

  //let bodyDisplay: 'none' | 'flex' = 'none';

  const OnMouseEnter = () => {
    document.getElementById(`${props.id}-body`).style.display = "flex";
  }
  const OnMouseLeave = () => {
    document.getElementById(`${props.id}-body`).style.display = "none";
  }
  
</script>

<div
  id={props.id}
  aria-label={props["aria-label"]}
  role="tooltip"
  class={`pop-menu-container ${props.className}`}
  onmouseleave={OnMouseLeave}
>
  <div id={`${props.id}-trigger`} role="tooltip" class="pop-menu-trigger" onmouseenter={OnMouseEnter}>
    {@render props.trigger()}
  </div>
  <div id={`${props.id}-body`} class="pop-menu-body bg-darker-bg">
    {@render props.body()}
  </div>
</div>

<style lang="scss">
  .pop-menu {
    &-body {
      position: absolute;
      top: 4rem;
      z-index: 10;
      padding: 0.5rem;
      box-shadow: 1px 1px 1px #000;
      background-color: #111;
      display: flex;
      flex-direction: column;
    }
    &-trigger {
      padding-left: 0.5rem;
      overflow: hidden;
    }
    &-container {
      overflow: hidden;
      margin: 0;
    }
  }
</style>
